Use imagePullCredentials when using private docker images
wso2/kubernetes-sp pull request #48
Opened 2019-05-31 11:37 UTC by Aaquiff

## Purpose
Add conditional use of imagePullCredentials when using WSO2 private docker registry in helm charts.

2019-05-31 19:07 UTC, chirangaalwis requested changes

2019-05-31 19:07 UTC, chirangaalwis commented on helm/pattern-distributed/pattern-distributed/templates/wso2sp-dashboard-deployment.yaml
> +      {{ end }}
@Aaquiff Can you please add an EOF new line?

2019-05-31 19:07 UTC, chirangaalwis commented on helm/pattern-distributed/pattern-distributed/templates/wso2sp-manager-1-deployment.yaml
> +      {{ end }}
@Aaquiff Can you please add an EOF new line?

2019-05-31 19:07 UTC, chirangaalwis commented on helm/pattern-distributed/pattern-distributed/templates/wso2sp-manager-2-deployment.yaml
> +      {{ end }}
@Aaquiff Can you please add an EOF new line?

2019-06-03 06:10 UTC, KavinduZoysa approved these changes

2019-06-03 06:52 UTC, chirangaalwis approved these changes

2019-06-03 06:53 UTC, merged